"""Terminal preview and naming_preview.md generation."""

from collections import defaultdict
from pathlib import Path

from rich.console import Console
from rich.table import Table
from rich import box

from scalecut.models import ProjectConfig
from scalecut.naming import generate_all_filenames, sanitize
from scalecut.folders import build_folder_tree
from scalecut import __version__

console = Console()


def show_preview(config: ProjectConfig) -> None:
    """Print a full preview of what ScaleCut will generate (terminal)."""
    deliverables = generate_all_filenames(config)

    console.print()
    console.rule("[bold cyan]ScaleCut — Project Preview[/bold cyan]")
    console.print()

    info = Table(box=box.SIMPLE, show_header=False, padding=(0, 2))
    info.add_column(style="bold cyan", no_wrap=True)
    info.add_column(style="white")
    info.add_row("Client",       config.client)
    info.add_row("Project",      config.project)
    info.add_row("Type",         config.project_type)
    info.add_row("Delivery",     config.delivery_date)
    info.add_row("Clips",        str(config.num_clips))
    info.add_row("Platforms",    ", ".join(config.platforms))
    info.add_row("Formats",      ", ".join(config.formats))
    info.add_row("Language",     config.language)
    info.add_row("Version",      f"V{config.version.zfill(2)}")
    info.add_row("Status",       config.initial_status)
    info.add_row("Output path",  config.output_path)
    info.add_row("Deliverables", str(len(deliverables)))
    console.print(info)

    console.print("[bold cyan]Folder structure[/bold cyan]")
    root_name = config.folder_name()
    console.print(f"  [bold yellow]{root_name}/[/bold yellow]")
    for folder in build_folder_tree(config):
        console.print(f"    [dim]{folder}/[/dim]")
    console.print()

    console.print("[bold cyan]Export name preview[/bold cyan] [dim](first 10)[/dim]")
    table = Table(box=box.SIMPLE_HEAD, show_lines=False)
    table.add_column("Clip",     style="bold", no_wrap=True)
    table.add_column("Platform", style="cyan")
    table.add_column("Format",   style="magenta")
    table.add_column("Status",   style="yellow")
    table.add_column("Filename", style="green")

    for d in deliverables[:10]:
        table.add_row(d["clip"], d["platform"], d["format"], d["status"], d["filename"])

    if len(deliverables) > 10:
        table.add_row("...", "...", "...", "...", f"... ({len(deliverables) - 10} more)")

    console.print(table)
    console.print()


def write_naming_preview(config: ProjectConfig, root: Path) -> Path:
    """Write 10_Admin/naming_preview.md with all filenames grouped by clip."""
    deliverables = generate_all_filenames(config)
    out = root / "10_Admin" / "naming_preview.md"

    client_slug  = sanitize(config.client)
    project_slug = sanitize(config.project)
    date_slug    = config.delivery_date.replace("-", "")
    version_slug = f"V{config.version.zfill(2)}"

    by_clip: dict[str, list] = defaultdict(list)
    for d in deliverables:
        by_clip[d["clip"]].append(d)

    lines = [
        "# Naming Preview",
        f"## {config.client} — {config.project}",
        "",
        f"> Generated by **ScaleCut v{__version__}**",
        "",
        "---",
        "",
        "## Naming pattern",
        "",
        "```",
        "CLIENT_PROJECT_ClipNN_PLATFORM_FORMAT_YYYYMMDD_VNN.mp4",
        "```",
        "",
        "| Token | Value |",
        "|-------|-------|",
        f"| CLIENT | `{client_slug}` |",
        f"| PROJECT | `{project_slug}` |",
        f"| Date | `{date_slug}` |",
        f"| Version | `{version_slug}` |",
        f"| Platforms | {', '.join(config.platforms)} |",
        f"| Formats | {', '.join(config.formats)} |",
        "",
        "---",
        "",
        f"## All filenames — {len(deliverables)} total",
        "",
    ]

    for clip, items in by_clip.items():
        lines += [f"### {clip}", ""]
        lines += [
            "| Platform | Format | Filename |",
            "|----------|--------|----------|",
        ]
        for d in items:
            lines.append(f"| {d['platform']} | {d['format']} | `{d['filename']}` |")
        lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    return out
