"""Generate prompts_ai.md — ready-to-copy AI prompts using real project data."""

from pathlib import Path
from scalecut.models import ProjectConfig
from scalecut import __version__


def write_prompts_ai(config: ProjectConfig, root: Path) -> Path:
    out = root / "10_Admin" / "prompts_ai.md"

    platforms_str = ", ".join(config.platforms)
    formats_str   = ", ".join(config.formats)
    lang          = config.language
    client        = config.client
    project       = config.project
    proj_type     = config.project_type
    num_clips     = config.num_clips
    version       = f"V{config.version.zfill(2)}"

    lines = [
        "# AI Prompts",
        f"## {client} — {project}",
        "",
        f"> Generado por **ScaleCut v{__version__}**  ",
        "> Usa estos prompts con ChatGPT, Claude, Gemini o cualquier LLM.",
        "> Los datos del proyecto ya están incorporados — copia, pega y completa las secciones marcadas con `[ ]`.",
        "",
        "---",
        "",
        "## 1. Selección de clips desde transcripción",
        "",
        "```",
        f"Eres un editor de video y content strategist especializado en {lang} para marcas.",
        "",
        f"Estás trabajando en el proyecto \"{project}\" para el cliente \"{client}\".",
        f"Tipo de contenido: {proj_type}",
        f"Plataformas objetivo: {platforms_str}",
        f"Idioma: {lang}",
        "",
        f"Analiza la siguiente transcripción e identifica los {num_clips} mejores momentos",
        "para convertir en clips de redes sociales.",
        "",
        "Para cada clip propuesto, incluye:",
        "1. Timestamp aproximado (inicio → fin)",
        "2. Duración estimada",
        "3. Por qué es un buen clip (hook, valor, emoción, dato)",
        f"4. Plataforma más adecuada de: {platforms_str}",
        "5. Formato recomendado y por qué",
        "",
        "Criterios de selección:",
        "- Tiene un hook claro en los primeros 3 segundos",
        "- Aporta valor real, genera emoción o curiosidad",
        "- Puede entenderse sin contexto previo",
        f"- Duración ideal: 30–90 s para vertical, hasta 3 min para 16x9",
        "",
        "TRANSCRIPCIÓN:",
        "[ pega aquí la transcripción ]",
        "```",
        "",
        "---",
        "",
        "## 2. Generación de hooks",
        "",
        "```",
        f"Eres un copywriter experto en redes sociales en {lang}.",
        f"Cliente: {client} | Proyecto: {project}",
        f"Plataformas: {platforms_str}",
        "",
        "Para el clip descrito abajo, genera 5 hooks alternativos.",
        "",
        "Reglas:",
        "- El hook debe durar máx 3 segundos hablado",
        "- Empezar con acción, pregunta, dato o afirmación fuerte",
        "- NO empezar con 'Hola', presentación del speaker ni del podcast",
        "- Tono conversacional para TikTok/Reels, profesional para LinkedIn",
        "- En idioma: " + lang,
        "",
        "Para cada hook indica:",
        "- El texto del hook",
        f"- Plataforma recomendada de: {platforms_str}",
        "- Por qué funciona",
        "",
        "DESCRIPCIÓN DEL CLIP:",
        "[ describe el clip aquí ]",
        "```",
        "",
        "---",
        "",
        "## 3. Generación de captions",
        "",
        "```",
        f"Eres un social media copywriter en {lang}.",
        f"Cliente: {client} | Proyecto: {project}",
        "",
        f"Escribe captions para el siguiente clip. Genera una versión por plataforma:",
        "",
    ]

    for platform in config.platforms:
        if platform in ("Instagram Reels", "TikTok", "YouTube Shorts"):
            style = "conversacional, con emojis, máx 150 caracteres + hashtags"
        elif platform == "LinkedIn":
            style = "profesional, reflexivo, 100–300 caracteres, sin exceso de emojis"
        else:
            style = "claro y directo, adaptado a la plataforma"
        lines.append(f"- **{platform}**: {style}")

    lines += [
        "",
        "Para cada caption incluye:",
        "- Texto principal",
        "- 5 hashtags relevantes",
        "- CTA sugerido",
        "",
        "DESCRIPCIÓN DEL CLIP:",
        "[ describe el clip aquí ]",
        "```",
        "",
        "---",
        "",
        "## 4. Generación de títulos",
        "",
        "```",
        f"Eres un SEO y content strategist en {lang}.",
        f"Cliente: {client} | Proyecto: {project} | Tipo: {proj_type}",
        "",
        "Genera 5 títulos alternativos para el siguiente clip.",
        "",
        "Requisitos por plataforma:",
        "- YouTube / YouTube Shorts: incluir keyword principal, máx 60 caracteres",
        "- Instagram Reels: emocional, intrigante, máx 40 caracteres",
        "- TikTok: directo, con número o dato si aplica, máx 50 caracteres",
        "- LinkedIn: orientado al aprendizaje o resultado profesional",
        "",
        "Para cada título indica plataforma y por qué funciona.",
        "",
        "TEMA / DESCRIPCIÓN DEL CLIP:",
        "[ describe el clip aquí ]",
        "```",
        "",
        "---",
        "",
        "## 5. Generación de CTAs",
        "",
        "```",
        f"Eres un conversion copywriter en {lang}.",
        f"Cliente: {client} | Proyecto: {project}",
        f"Plataformas: {platforms_str}",
        "",
        "Genera 3 CTAs distintos para el siguiente clip.",
        "",
        "Tipos de CTA a incluir:",
        "- Engagement (guardar, compartir, comentar)",
        "- Seguimiento (seguir, suscribirse)",
        "- Conversión (visitar web, descargar, agendar)",
        "",
        "Para cada CTA:",
        "- Texto exacto (máx 15 palabras)",
        f"- Plataforma más adecuada de: {platforms_str}",
        "- Tipo de CTA",
        "- Posición sugerida en el video (inicio / mitad / final)",
        "",
        "CONTEXTO DEL CLIP:",
        "[ describe el clip y el objetivo del cliente aquí ]",
        "```",
        "",
        "---",
        "",
        "## 6. Revisión QA de entregables",
        "",
        "```",
        f"Eres un quality assurance specialist para producción de video en {lang}.",
        f"Cliente: {client} | Proyecto: {project} | Versión: {version}",
        f"Total de entregables: {num_clips} clips × {len(config.platforms)} plataformas × {len(config.formats)} formatos",
        "",
        "Revisa el siguiente entregable y evalúa cada punto:",
        "",
        "CHECKLIST DE QA:",
        "[ ] El filename sigue la convención: CLIENT_PROJECT_ClipNN_PLATFORM_FORMAT_DATE_VNN.mp4",
        "[ ] La resolución es correcta para el formato indicado",
        "[ ] El hook aparece en los primeros 3 segundos",
        "[ ] Los subtítulos están sincronizados y sin errores ortográficos",
        "[ ] El audio está normalizado (-14 LUFS para streaming)",
        "[ ] No hay frames negros al inicio ni al final",
        "[ ] El formato de color es correcto (Rec.709 para digital)",
        "[ ] La duración es adecuada para la plataforma",
        "[ ] El CTA aparece en el lugar correcto",
        f"[ ] El contenido es apropiado para: {platforms_str}",
        "",
        "ENTREGABLE A REVISAR:",
        "[ nombre del archivo y descripción ]",
        "",
        "Indica para cada punto: ✓ OK / ✗ Problema / — No aplica",
        "Si hay problemas, describe qué debe corregirse.",
        "```",
        "",
    ]

    out.write_text("\n".join(lines), encoding="utf-8")
    return out
