"""Generate project README.md."""

from pathlib import Path
from scalecut.models import ProjectConfig
from scalecut.templates import PROJECT_TEMPLATES
from scalecut import __version__


def write_readme(config: ProjectConfig, root: Path) -> Path:
    template_info = PROJECT_TEMPLATES.get(config.project_type, {})
    description   = template_info.get("description", "")
    notes         = template_info.get("notes", "")
    total         = config.num_clips * len(config.platforms) * len(config.formats)

    lines = [
        f"# {config.client} — {config.project}",
        "",
        f"> Generated by **ScaleCut v{__version__}** · {config.created_at[:10]}",
        "",
        "---",
        "",
        "## Project info",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Client | {config.client} |",
        f"| Project | {config.project} |",
        f"| Type | {config.project_type} |",
        f"| Delivery | {config.delivery_date} |",
        f"| Language | {config.language} |",
        f"| Version | V{config.version.zfill(2)} |",
        f"| Status | {config.initial_status} |",
        f"| Clips | {config.num_clips} |",
        f"| Platforms | {', '.join(config.platforms)} |",
        f"| Formats | {', '.join(config.formats)} |",
        f"| Total deliverables | **{total}** |",
        "",
    ]

    if description:
        lines += [
            "---",
            "",
            "## Template notes",
            "",
            f"**{config.project_type}** — {description}",
        ]
        if notes:
            lines += ["", f"> {notes}"]
        lines.append("")

    lines += [
        "---",
        "",
        "## Folder structure",
        "",
        "```",
        f"{root.name}/",
        "  01_Footage/",
        "  02_Audio/",
        "  03_Graphics/",
        "  04_Project_Files/",
        "  05_Sequences/",
        "  06_Subtitles/",
        "  07_Exports/",
    ]
    for fmt in config.formats:
        lines.append(f"    {fmt}/")
    lines += [
        "  08_Delivery/",
        "  09_References/",
        "  10_Admin/",
        "```",
        "",
        "---",
        "",
        "## Naming convention",
        "",
        "```",
        "CLIENT_PROJECT_ClipNN_PLATFORM_FORMAT_YYYYMMDD_VNN.mp4",
        "```",
        "",
        "**Example:**",
        "```",
    ]

    from scalecut.naming import sanitize
    client_slug  = sanitize(config.client)
    project_slug = sanitize(config.project)
    date_slug    = config.delivery_date.replace("-", "")
    lines += [
        f"{client_slug}_{project_slug}_Clip01_INSTA_9x16_{date_slug}_V{config.version.zfill(2)}.mp4",
        "```",
        "",
        "---",
        "",
        "## Workflow",
        "",
        "1. Drop raw footage in `01_Footage/`",
        "2. Save project files in `04_Project_Files/`",
        "3. Export sequences to `07_Exports/{format}/` using the names in `naming_preview.md`",
        "4. Track progress in `10_Admin/delivery_checklist.csv`",
        "5. Move approved deliverables to `08_Delivery/`",
        "",
        "---",
        "",
        "## Files in `10_Admin/`",
        "",
        "| File | Purpose |",
        "|------|---------|",
        "| `delivery_checklist.csv` | Deliverable tracker — import into Google Sheets / Notion |",
        "| `delivery_checklist.md` | Deliverable tracker — checkboxes grouped by clip |",
        "| `naming_preview.md` | All export filenames grouped by clip and platform |",
        "| `project_config.json` | Machine-readable project data for tooling |",
        "",
    ]

    out = root / "README.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out
