"""Generate project README.md."""

from pathlib import Path
from scalecut.models import ProjectConfig
from scalecut.templates import PROJECT_TEMPLATES
from scalecut import __version__


def write_readme(config: ProjectConfig, root: Path) -> Path:
    template_info = PROJECT_TEMPLATES.get(config.project_type, {})
    description  = template_info.get("description", "")
    notes        = template_info.get("notes", "")

    total_deliverables = config.num_clips * len(config.platforms) * len(config.formats)

    lines = [
        f"# {config.client} — {config.project}",
        "",
        f"> Generated by **ScaleCut v{__version__}** on {config.created_at[:10]}",
        "",
        "---",
        "",
        "## Project Info",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Client | {config.client} |",
        f"| Project | {config.project} |",
        f"| Type | {config.project_type} |",
        f"| Delivery date | {config.delivery_date} |",
        f"| Language | {config.language} |",
        f"| Initial version | V{config.version.zfill(2)} |",
        f"| Initial status | {config.initial_status} |",
        f"| Clips | {config.num_clips} |",
        f"| Platforms | {', '.join(config.platforms)} |",
        f"| Formats | {', '.join(config.formats)} |",
        f"| Total deliverables | {total_deliverables} |",
        "",
        "---",
        "",
        "## Template",
        "",
        f"**{config.project_type}**",
    ]

    if description:
        lines += ["", description]
    if notes:
        lines += ["", f"> {notes}"]

    lines += [
        "",
        "---",
        "",
        "## Folder Structure",
        "",
        "```",
        f"{root.name}/",
        "  01_Footage/",
        "  02_Audio/",
        "  03_Graphics/",
        "  04_Project_Files/",
        "  05_Sequences/",
        "  06_Subtitles/",
        "  07_Exports/",
    ]
    for fmt in config.formats:
        lines.append(f"    {fmt}/")
    lines += [
        "  08_Delivery/",
        "  09_References/",
        "  10_Admin/",
        "```",
        "",
        "---",
        "",
        "## Naming Convention",
        "",
        "```",
        "Cliente_Proyecto_ClipNN_Plataforma_Formato_Fecha_VNN.mp4",
        "```",
        "",
        "---",
        "",
        "## Workflow",
        "",
        "1. Drop raw footage in `01_Footage/`",
        "2. Drop audio assets in `02_Audio/`",
        "3. Save project files in `04_Project_Files/`",
        "4. Export sequences to `07_Exports/{format}/`",
        "5. Move approved deliverables to `08_Delivery/`",
        "6. Update `10_Admin/checklist.csv` or `checklist.md` as pieces progress",
        "",
        "---",
        "",
        "## Files in 10_Admin",
        "",
        "| File | Purpose |",
        "|------|---------|",
        "| `project_config.json` | Machine-readable project data |",
        "| `checklist.csv` | Deliverable tracker (spreadsheet-friendly) |",
        "| `checklist.md` | Deliverable tracker (human-readable) |",
        "| `README.md` | This file |",
        "",
    ]

    out = root / "README.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out
