/**
 * ScaleCut × Adobe Premiere Pro — Prototype Scaffold
 * ====================================================
 * Version: 0.1.0-prototype
 * Language: ExtendScript (ECMAScript 3 + Adobe extensions)
 *
 * PURPOSE
 * -------
 * This script reads a ScaleCut edit_plan.json (or markers.csv) and uses
 * Premiere Pro's ExtendScript API to:
 *   1. Create markers on the active sequence for each clip.
 *   2. Create subsequences from in/out timecodes.
 *   3. Create one sequence per deliverable (clip × platform × format).
 *   4. Apply ScaleCut's naming convention to export jobs.
 *
 * This file is a documented scaffold — not all functions are fully
 * operational yet. Each function is marked with its implementation status:
 *   ✅ READY    — works as-is
 *   🔧 PARTIAL  — works with caveats (see notes)
 *   📋 PLANNED  — shows intent; needs real Premiere project to test fully
 *
 * HOW TO RUN (two paths)
 * ----------------------
 * Path A — Quick test (no panel needed):
 *   1. Open a Premiere Pro project.
 *   2. File > Scripts > Run Script File…
 *   3. Select this file.
 *   4. The script runs in the current project context.
 *
 * Path B — CEP Panel (production plugin, future phase):
 *   1. Package this script inside a CEP extension folder.
 *   2. The HTML/JS panel calls this via:
 *        csInterface.evalScript("ScaleCut.runFromPanel(editPlanPath)");
 *   3. The panel handles the UI; this script handles all Premiere logic.
 *
 * PREMIERE PRO API REFERENCE
 * --------------------------
 * Key objects used in this script:
 *   app.project                        Current open project
 *   app.project.activeSequence         Currently selected sequence
 *   app.project.sequences              All sequences in the project
 *   app.project.rootItem               Root bin (ProjectItem)
 *   app.project.createNewSequence()    Create a new empty sequence
 *   sequence.markers                   MarkerCollection on a sequence
 *   sequence.markers.createMarker()    Add a marker (takes time in seconds)
 *   app.encoder.encodeSequence()       Hand off to Adobe Media Encoder
 *
 * Timecode note:
 *   Premiere's internal time unit is "ticks" (254,016,000,000 per second).
 *   Markers, however, accept and return plain seconds (float).
 *   This script converts ScaleCut's HH:MM:SS:FF to seconds before
 *   interacting with Premiere's API.
 *
 * SCALECUT DATA FLOW
 * ------------------
 *   ScaleCut CLI / Streamlit UI
 *        │
 *        ├── edit_plan.json   ← primary data source for this script
 *        │     • timecodes per clip
 *        │     • goals, hooks, notes
 *        │     • export_filename per deliverable
 *        │
 *        └── markers.csv     ← fallback / alternative data source
 *              • one row per deliverable
 *              • color per platform
 *
 *   edit_plan.json / markers.csv
 *        │
 *        ▼
 *   prototype.jsx (this file)
 *        │
 *        ├── createMarkersFromEditPlan()      → markers on master sequence
 *        ├── createSubsequenceFromTimecodes() → new sequence per clip
 *        ├── createSequencesForDeliverables() → one seq per deliverable
 *        └── applyExportNaming()              → AME export queue
 *
 * @namespace ScaleCut
 */

// ── Namespace ─────────────────────────────────────────────────────────────────

var ScaleCut = ScaleCut || {};

// ── Constants ─────────────────────────────────────────────────────────────────

/** @const {number} Premiere's internal tick rate (ticks per second). */
ScaleCut.TICKS_PER_SECOND = 254016000000;

/** @const {number} Default frame rate when not specified in edit_plan.json. */
ScaleCut.DEFAULT_FPS = 25;

/**
 * Marker type codes accepted by Premiere Pro.
 * @const
 */
ScaleCut.MARKER_TYPES = {
    COMMENT:      0,
    CHAPTER:      1,
    SEGMENTATION: 2,
    WEB_LINK:     3
};

/**
 * Platform → marker color mapping.
 * Matches the colors generated by ScaleCut's markers.csv.
 * @const
 */
ScaleCut.PLATFORM_COLORS = {
    "Instagram Reels": "Cyan",
    "TikTok":          "Magenta",
    "LinkedIn":        "Blue",
    "YouTube":         "Red",
    "YouTube Shorts":  "Orange",
    "Stories":         "Yellow",
    "Facebook":        "Purple",
    "Ads":             "Green",
    "Website":         "White"
};


// ── File I/O ──────────────────────────────────────────────────────────────────

/**
 * Read and parse a ScaleCut edit_plan.json file.
 * Status: ✅ READY
 *
 * @param  {string} filePath  Absolute path to edit_plan.json.
 * @return {Object|null}      Parsed edit plan object, or null on error.
 *
 * @example
 *   var plan = ScaleCut.readEditPlanJson(
 *     "/Users/editor/Desktop/ScaleCut_Projects/ACME_PODCAST_20241220/10_Admin/edit_plan.json"
 *   );
 *   $.writeln("Total clips: " + plan.edit_plan.length);
 */
ScaleCut.readEditPlanJson = function(filePath) {
    var file = new File(filePath);

    if (!file.exists) {
        ScaleCut.log("ERROR: edit_plan.json not found at: " + filePath);
        return null;
    }

    file.open("r");
    var content = file.read();
    file.close();

    if (!content || content.length === 0) {
        ScaleCut.log("ERROR: edit_plan.json is empty.");
        return null;
    }

    try {
        // ExtendScript (ES3) does not guarantee JSON.parse — use eval safely.
        // In Premiere CC 2020+ you can use JSON.parse() directly.
        var data = (typeof JSON !== "undefined")
            ? JSON.parse(content)
            : eval("(" + content + ")");

        ScaleCut.log("Loaded edit_plan.json: " + data.edit_plan.length + " clips, mode=" + data.mode);
        return data;
    } catch (e) {
        ScaleCut.log("ERROR parsing edit_plan.json: " + e.message);
        return null;
    }
};


/**
 * Read and parse a ScaleCut markers.csv file.
 * Status: ✅ READY
 *
 * @param  {string} filePath  Absolute path to markers.csv.
 * @return {Array|null}       Array of row objects, or null on error.
 *
 * @example
 *   var markers = ScaleCut.readMarkersCsv(
 *     "/Users/editor/.../10_Admin/markers.csv"
 *   );
 */
ScaleCut.readMarkersCsv = function(filePath) {
    var file = new File(filePath);

    if (!file.exists) {
        ScaleCut.log("ERROR: markers.csv not found at: " + filePath);
        return null;
    }

    file.open("r");
    var headers = file.readln().split(",");
    var rows    = [];

    while (!file.eof) {
        var line = file.readln();
        if (!line || line.length === 0) continue;

        var values = line.split(",");
        var row    = {};
        for (var i = 0; i < headers.length; i++) {
            row[headers[i].replace(/\r/g, "")] = (values[i] || "").replace(/\r/g, "");
        }
        rows.push(row);
    }

    file.close();
    ScaleCut.log("Loaded markers.csv: " + rows.length + " rows.");
    return rows;
};


// ── Timecode utilities ────────────────────────────────────────────────────────

/**
 * Convert a ScaleCut HH:MM:SS:FF timecode to seconds (float).
 * Premiere Pro's marker API accepts time in seconds.
 * Status: ✅ READY
 *
 * @param  {string} tc   Timecode string, e.g. "00:01:25:12".
 * @param  {number} fps  Frame rate (default 25).
 * @return {number}      Time in seconds, or 0 if tc is empty/invalid.
 */
ScaleCut.timecodeToSeconds = function(tc, fps) {
    fps = fps || ScaleCut.DEFAULT_FPS;

    if (!tc || tc.length === 0) return 0;

    var parts = tc.split(":");
    if (parts.length !== 4) return 0;

    var h = parseInt(parts[0], 10) || 0;
    var m = parseInt(parts[1], 10) || 0;
    var s = parseInt(parts[2], 10) || 0;
    var f = parseInt(parts[3], 10) || 0;

    return h * 3600 + m * 60 + s + (f / fps);
};


/**
 * Convert seconds (float) back to HH:MM:SS:FF timecode.
 * Useful for displaying Premiere's time values in ScaleCut format.
 * Status: ✅ READY
 *
 * @param  {number} seconds
 * @param  {number} fps
 * @return {string}  e.g. "00:01:25:12"
 */
ScaleCut.secondsToTimecode = function(seconds, fps) {
    fps = fps || ScaleCut.DEFAULT_FPS;

    var totalFrames = Math.round(seconds * fps);
    var f  = totalFrames % fps;
    var ts = Math.floor(totalFrames / fps);
    var s  = ts % 60;
    var tm = Math.floor(ts / 60);
    var mn = tm % 60;
    var h  = Math.floor(tm / 60);

    function pad(n) { return (n < 10 ? "0" : "") + n; }
    return pad(h) + ":" + pad(mn) + ":" + pad(s) + ":" + pad(f);
};


// ── Core functions ────────────────────────────────────────────────────────────

/**
 * Find and return the active sequence in the current Premiere project.
 * Status: ✅ READY
 *
 * Falls back to the first sequence in the project if none is active.
 * Logs an error if the project has no sequences at all.
 *
 * @return {Sequence|null}
 */
ScaleCut.findActiveSequence = function() {
    if (!app.project) {
        ScaleCut.log("ERROR: No project open in Premiere Pro.");
        return null;
    }

    var seq = app.project.activeSequence;

    if (!seq) {
        ScaleCut.log("WARNING: No active sequence. Trying first available sequence…");

        if (app.project.sequences.numSequences > 0) {
            seq = app.project.sequences[0];
            ScaleCut.log("Using sequence: " + seq.name);
        } else {
            ScaleCut.log("ERROR: Project has no sequences. Create a sequence first.");
            return null;
        }
    }

    ScaleCut.log("Active sequence: " + seq.name + " (" + seq.frameSizeHorizontal + "x" + seq.frameSizeVertical + ")");
    return seq;
};


/**
 * Create a new subsequence from the timecodes of a single EditPlanClip.
 *
 * Status: 📋 PLANNED
 *
 * Implementation notes for the real version:
 *   1. Locate the source clip(s) in the project bins that correspond to
 *      this clip_id. Naming convention: the clip file should live in
 *      01_Footage/ and its name should contain the clip_id.
 *   2. Use app.project.createNewSequence() with the correct preset for
 *      the target format (9x16 → vertical preset, 16x9 → standard, etc.).
 *   3. Insert the source clip into the new sequence using
 *      sequence.videoTracks[0].insertClip(projectItem, insertTime).
 *   4. Set in/out points on the clip using clip.inPoint and clip.outPoint.
 *   5. Name the sequence using ScaleCut's naming convention.
 *
 * API reference:
 *   app.project.createNewSequence(seqName, presetPath)
 *   track.insertClip(projectItem, time)            — inserts at time (seconds)
 *   track.clips[i].inPoint                         — in point (Time object)
 *   track.clips[i].outPoint                        — out point (Time object)
 *
 * @param  {Object}   clip      One item from edit_plan.json's edit_plan array.
 * @param  {Sequence} masterSeq The master sequence containing the full footage.
 * @param  {number}   fps       Frame rate of the project.
 * @return {Sequence|null}      The new subsequence, or null if not yet implemented.
 */
ScaleCut.createSubsequenceFromTimecodes = function(clip, masterSeq, fps) {
    fps = fps || ScaleCut.DEFAULT_FPS;

    if (!clip.start_timecode || !clip.end_timecode) {
        ScaleCut.log("SKIP " + clip.clip_id + ": no timecodes (placeholder mode).");
        return null;
    }

    var startSec = ScaleCut.timecodeToSeconds(clip.start_timecode, fps);
    var endSec   = ScaleCut.timecodeToSeconds(clip.end_timecode,   fps);
    var seqName  = clip.clip_id + "_" + clip.platform.replace(/ /g, "_") + "_" + clip.format;

    ScaleCut.log("[PLANNED] createSubsequenceFromTimecodes: " + seqName +
                 " (" + clip.start_timecode + " → " + clip.end_timecode + ")");

    // ── TODO: real implementation ──────────────────────────────────────────
    //
    // var presetPath = ScaleCut.getPresetForFormat(clip.format);
    // var newSeq = app.project.createNewSequence(seqName, presetPath);
    //
    // var sourceClip = ScaleCut.findSourceClipById(clip.clip_id);
    // if (!sourceClip) return null;
    //
    // newSeq.videoTracks[0].insertClip(sourceClip, 0);
    // var trackClip = newSeq.videoTracks[0].clips[0];
    // trackClip.inPoint  = startSec;   // or via Time object
    // trackClip.outPoint = endSec;
    //
    // return newSeq;
    // ──────────────────────────────────────────────────────────────────────

    return null; // placeholder — remove when implemented
};


/**
 * Create Premiere Pro markers on the active sequence for every clip
 * in the edit plan that has timecodes.
 *
 * Status: 🔧 PARTIAL
 * Works when the active sequence exists and clips have timecodes.
 * Skips placeholder clips (empty start_timecode).
 *
 * @param  {Object}   editPlanData  Parsed edit_plan.json object.
 * @param  {Sequence} [sequence]    Target sequence. Uses active if omitted.
 * @return {number}                 Count of markers created.
 */
ScaleCut.createMarkersFromEditPlan = function(editPlanData, sequence) {
    sequence = sequence || ScaleCut.findActiveSequence();
    if (!sequence) return 0;

    var fps     = editPlanData.fps || ScaleCut.DEFAULT_FPS;
    var clips   = editPlanData.edit_plan || [];
    var created = 0;
    var seen    = {}; // deduplicate: one marker per clip_id (not per deliverable)

    for (var i = 0; i < clips.length; i++) {
        var clip = clips[i];

        // Skip placeholders and already-processed clip_ids
        if (!clip.start_timecode || seen[clip.clip_id]) continue;
        seen[clip.clip_id] = true;

        var startSec = ScaleCut.timecodeToSeconds(clip.start_timecode, fps);
        var endSec   = ScaleCut.timecodeToSeconds(clip.end_timecode,   fps);

        // Build a readable comment from ScaleCut's creative fields
        var commentParts = [];
        if (clip.goal)  commentParts.push("Goal: " + clip.goal);
        if (clip.hook)  commentParts.push("Hook: " + clip.hook);
        if (clip.notes) commentParts.push(clip.notes);

        // ── Premiere API call ──────────────────────────────────────────────
        var marker      = sequence.markers.createMarker(startSec);
        marker.name     = clip.clip_id + (clip.title ? " — " + clip.title : "");
        marker.comments = commentParts.join(" | ");
        marker.end      = endSec;
        marker.type     = ScaleCut.MARKER_TYPES.COMMENT;
        // ──────────────────────────────────────────────────────────────────

        ScaleCut.log("Marker created: " + marker.name +
                     " [" + clip.start_timecode + " → " + clip.end_timecode + "]");
        created++;
    }

    ScaleCut.log("createMarkersFromEditPlan: " + created + " markers created.");
    return created;
};


/**
 * Create one Premiere Pro sequence per deliverable in the edit plan.
 * Deliverables are unique combinations of clip_id × platform × format.
 *
 * Status: 📋 PLANNED
 *
 * When complete, this function will:
 *   - Create sequences named with ScaleCut's naming convention.
 *   - Set each sequence's frame size to match the format (9x16, 1x1, 16x9).
 *   - Populate each sequence with the source clip trimmed to its timecodes.
 *   - Organize sequences into bins named by clip_id.
 *
 * API reference:
 *   app.project.createNewSequence(name, presetPath)
 *   app.project.rootItem.createBin(name)
 *   bin.moveBin(targetBin)
 *
 * @param  {Object} editPlanData  Parsed edit_plan.json object.
 * @return {Array}                List of created sequence names (or planned names).
 */
ScaleCut.createSequencesForDeliverables = function(editPlanData) {
    var fps   = editPlanData.fps || ScaleCut.DEFAULT_FPS;
    var clips = editPlanData.edit_plan || [];
    var names = [];

    // Group deliverables by clip_id
    var byClip = {};
    for (var i = 0; i < clips.length; i++) {
        var clip = clips[i];
        if (!byClip[clip.clip_id]) byClip[clip.clip_id] = [];
        byClip[clip.clip_id].push(clip);
    }

    for (var clipId in byClip) {
        var deliverables = byClip[clipId];

        ScaleCut.log("[PLANNED] Creating bin: " + clipId);
        // TODO: var bin = app.project.rootItem.createBin(clipId);

        for (var j = 0; j < deliverables.length; j++) {
            var d       = deliverables[j];
            var seqName = ScaleCut.buildSequenceName(d);
            names.push(seqName);

            ScaleCut.log("[PLANNED] Sequence: " + seqName);

            // ── TODO: real implementation ──────────────────────────────────
            // var preset  = ScaleCut.getPresetForFormat(d.format);
            // var newSeq  = app.project.createNewSequence(seqName, preset);
            // ScaleCut.createSubsequenceFromTimecodes(d, masterSeq, fps);
            // newSeq.moveBin(bin);
            // ──────────────────────────────────────────────────────────────
        }
    }

    ScaleCut.log("createSequencesForDeliverables: " + names.length + " sequences planned.");
    return names;
};


/**
 * Apply ScaleCut's naming convention to an export job in Adobe Media Encoder.
 *
 * Status: 📋 PLANNED
 *
 * When complete, this function will:
 *   - Add the sequence to the AME render queue.
 *   - Set the output filename to match ScaleCut's export_filename.
 *   - Set the output folder to 07_Exports/{format}/ inside the project root.
 *   - Optionally start the render immediately.
 *
 * API reference:
 *   app.encoder.launchEncoder()
 *   app.encoder.encodeSequence(seq, outputPath, presetPath, removeFromQueue, startImmediately)
 *   app.encoder.bind("onEncoderJobComplete", callback)
 *
 * @param  {Sequence} sequence        The sequence to export.
 * @param  {string}   exportFilename  ScaleCut filename, e.g. "ACME_Clip01_INSTA_9x16_20241220_V01.mp4"
 * @param  {string}   projectRoot     Absolute path to the ScaleCut project root folder.
 * @param  {string}   format          e.g. "9x16", "1x1", "16x9"
 * @param  {string}   [presetPath]    Path to an .epr export preset file.
 * @return {void}
 */
ScaleCut.applyExportNaming = function(sequence, exportFilename, projectRoot, format, presetPath) {
    if (!sequence) {
        ScaleCut.log("ERROR: No sequence provided to applyExportNaming.");
        return;
    }

    var outputFolder = projectRoot + "/07_Exports/" + format;
    var outputPath   = outputFolder + "/" + exportFilename;
    presetPath       = presetPath || ""; // use AME default if not specified

    ScaleCut.log("[PLANNED] Export: " + outputPath);
    ScaleCut.log("[PLANNED] Preset: " + (presetPath || "(AME default)"));

    // ── TODO: real implementation ──────────────────────────────────────────
    // app.encoder.launchEncoder();
    // app.encoder.encodeSequence(
    //     sequence,
    //     outputPath,
    //     presetPath,
    //     false,   // keep in queue after encoding
    //     false    // don't start AME queue automatically
    // );
    // ──────────────────────────────────────────────────────────────────────
};


// ── Format helpers ────────────────────────────────────────────────────────────

/**
 * Return the recommended sequence preset path for a given ScaleCut format.
 * Premiere Pro ships with built-in preset .sqpreset files.
 *
 * Status: 📋 PLANNED — preset paths are installation-dependent.
 *
 * @param  {string} format  "9x16", "1x1", or "16x9"
 * @return {Object}  { width, height, presetHint }
 */
ScaleCut.getPresetForFormat = function(format) {
    var presets = {
        "9x16":  { width: 1080, height: 1920, presetHint: "Vertical (1080x1920)" },
        "1x1":   { width: 1080, height: 1080, presetHint: "Square (1080x1080)"   },
        "16x9":  { width: 1920, height: 1080, presetHint: "HD 1080p (1920x1080)" }
    };
    return presets[format] || presets["16x9"];
};


/**
 * Build the Premiere sequence name from an EditPlanClip object.
 * Mirrors ScaleCut's naming convention so sequences are easy to identify.
 *
 * Status: ✅ READY
 *
 * @param  {Object} clip  One item from edit_plan.json.
 * @return {string}       e.g. "ACME_PODCAST_Clip01_INSTA_9x16"
 */
ScaleCut.buildSequenceName = function(clip) {
    return clip.export_filename
        ? clip.export_filename.replace(".mp4", "").replace(".mov", "").replace(".mxf", "")
        : clip.clip_id + "_" + clip.platform.replace(/ /g, "_") + "_" + clip.format;
};


// ── Logging ───────────────────────────────────────────────────────────────────

/**
 * Write a timestamped message to the ExtendScript console.
 * In a CEP panel context, messages would also appear in the browser console.
 *
 * @param {string} msg
 */
ScaleCut.log = function(msg) {
    var ts = "[ScaleCut] ";
    $.writeln(ts + msg);
};


// ── Main orchestrator ─────────────────────────────────────────────────────────

/**
 * Main entry point. Called when the script is run directly from
 * File > Scripts > Run Script File, or from a CEP panel via evalScript().
 *
 * Status: 🔧 PARTIAL — markers work; sequence creation is planned.
 *
 * @param  {string} editPlanPath  Absolute path to edit_plan.json.
 *                                Defaults to a hardcoded example path for quick testing.
 * @return {void}
 */
ScaleCut.run = function(editPlanPath) {
    ScaleCut.log("==================================================");
    ScaleCut.log("ScaleCut × Premiere Pro — Prototype v0.1.0");
    ScaleCut.log("==================================================");

    // ── 1. Resolve the edit_plan.json path ────────────────────────────────
    if (!editPlanPath) {
        // Default: look for edit_plan.json next to the current project file
        var projectPath = app.project.path;
        var projectDir  = projectPath.substring(0, projectPath.lastIndexOf("/"));
        editPlanPath    = projectDir + "/10_Admin/edit_plan.json";
        ScaleCut.log("No path provided — trying: " + editPlanPath);
    }

    // ── 2. Load the edit plan ─────────────────────────────────────────────
    var editPlan = ScaleCut.readEditPlanJson(editPlanPath);
    if (!editPlan) {
        ScaleCut.log("FATAL: Could not load edit_plan.json. Aborting.");
        return;
    }

    ScaleCut.log("Project: " + editPlan.project.client + " / " + editPlan.project.project);
    ScaleCut.log("Mode: " + editPlan.mode + " | Total clips: " + editPlan.edit_plan.length);

    // ── 3. Find / validate the active sequence ────────────────────────────
    var masterSeq = ScaleCut.findActiveSequence();
    if (!masterSeq) {
        ScaleCut.log("WARNING: Continuing without an active sequence (some features disabled).");
    }

    // ── 4. Create markers on the master sequence ──────────────────────────
    if (masterSeq) {
        var markersCreated = ScaleCut.createMarkersFromEditPlan(editPlan, masterSeq);
        ScaleCut.log("Markers on master sequence: " + markersCreated);
    }

    // ── 5. Plan subsequences for each deliverable ─────────────────────────
    var sequenceNames = ScaleCut.createSequencesForDeliverables(editPlan);
    ScaleCut.log("Sequences planned: " + sequenceNames.length);

    // ── 6. Summary ────────────────────────────────────────────────────────
    ScaleCut.log("--------------------------------------------------");
    ScaleCut.log("Done. Next steps:");
    ScaleCut.log("  • Fill timecodes in edit_plan.json (if in placeholder mode).");
    ScaleCut.log("  • Re-run the script after adding timecodes.");
    ScaleCut.log("  • When createSubsequenceFromTimecodes() is implemented,");
    ScaleCut.log("    each clip will get its own trimmed sequence automatically.");
    ScaleCut.log("==================================================");
};


// ── CEP panel bridge ──────────────────────────────────────────────────────────

/**
 * Entry point for calls from a CEP panel.
 * The HTML panel calls this via: csInterface.evalScript("ScaleCut.runFromPanel(path)")
 *
 * Returns a JSON string so the panel can display results in the UI.
 *
 * @param  {string} editPlanPath
 * @return {string}  JSON result string for the panel to parse.
 */
ScaleCut.runFromPanel = function(editPlanPath) {
    try {
        ScaleCut.run(editPlanPath);
        return JSON.stringify({ success: true, message: "Edit plan applied successfully." });
    } catch (e) {
        return JSON.stringify({ success: false, message: e.message });
    }
};


// ── Auto-run when executed as a standalone script ─────────────────────────────
// Comment this out when embedding in a CEP panel (the panel will call runFromPanel).

ScaleCut.run();
